### ISSUE TITLE
Get a list of all known currencies?

### ISSUE THREAD

**Issue by saurabhnanda** [k0001/safe-money#4] opened 2017-06-13 18:50 UTC
Is there any function that can provide the following data for all known currencies:

    (3-char alphanumeric code, unit, subunit, unicode currency code)

**Comment by k0001** [comment] 2017-06-30 13:36
@saurabhnanda sorry for the late reply, apparently I wasn't watching my own repo so I wasn't receiving notifications about new issues 😄 

Regarding your question: No, I don't think so. At least not without some clever type level hack I still don't know about. The reason for this is that currencies, by design, are intended to be an "open world", and enumerating stuff from an open world usually means "do it manually".

**Comment by k0001** [comment] 2017-07-02 09:46
It is possible to export a hardcoded list of all those values you ask from `safe-money`, at least for the currencies that `safe-money` export by default. Of course, a user would need to concatenate the data in this list with new currency data they add, but I think it can be a good starting point.

**Comment by k0001** [comment] 2017-12-10 15:07
@saurabhnanda I don't think it's worth exporting this from `safe-money`. Two reasons come to mind: First, the implementation would be that hardcoded list I mentioned, which is inherently bothersome to maintain, and it could give the wrong idea (that this list grows in size as you add more and more instances of `Scale`). Second, it's unlikely that the resulting list will be useful, since whatever you are building, it's unlikely you care about all of the fiat/metal/crypto currencies in the world. 

I'm gonna close this, please let me know if you have other thoughts.

**Closed by k0001** 2017-12-10 15:07 UTC
