### ISSUE TITLE
Unexpected result from denseToDecimal

### ISSUE THREAD

**Issue by ulfl** [k0001/safe-money#39] opened 2019-02-03 11:57 UTC
I get the following results from `denseToDecimal` (using version 0.7 of safe-money):
```haskell
> denseToDecimal Round False (Just ',') '.' 2 (1 % 1) (fromJust $ dense (1%1) :: Dense "USD")
Just "1.00"
> denseToDecimal Round False (Just ',') '.' 2 (1 % 1) (fromJust $ dense (1%10) :: Dense "USD")
Just "0.10"
> denseToDecimal Round False (Just ',') '.' 2 (1 % 1) (fromJust $ dense (1%100) :: Dense "USD")
Just "0.10"
```
Was expecting `0.01` in the last result.

**Comment by k0001** [comment] 2019-02-19 16:05
Hm, yes, I managed to reproduce this. There seems to be an issue when rendering values less than `0.10` USD. I'll investigate. Thanks.

Note that this is just a text rendering issue, not an issue on `Dense` or `Discrete`.

**Comment by k0001** [comment] 2019-03-18 18:48
@ulfl this has been fixed in `0.7.1`. The issue was that the necessary padding `0`s where being added after the `1`, rather than before the `1`. I added many tests covering this case as well.

**Closed** 2019-03-18 18:48 UTC

**Comment by ulfl** [comment] 2019-03-26 20:09
@k0001 Thanks for fixing and for an excellent library.
